[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "migration"]


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"


[dependencies]
config = "0.13.3"
actix-web = "4.2.1"
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.152", features = ["derive"] }
migration = { path = "migration" }
# Dev Dependencies are used exclusively when running tests or examples
# They do not get incuded in the final application binary!

# Core
[dependencies.sea-orm]
version = "0.10.7"
features = [
    "debug-print",
    "runtime-async-std-native-tls",
    "sqlx-postgres",
    "macros"
]

[dev-dependencies]
reqwest = "0.11.13"

